document.writeln("<div id=\'app\'>");
document.writeln("    <div id=\'title\' class=\'title\'>");
document.writeln("");
document.writeln("");
document.writeln("        <header class=\'col-12 \'>");
document.writeln("            <div class=\'navbar navbar-default\'>");
document.writeln("                <div class=\'nav navbar-nav navbar-left col-6\'>");
document.writeln("                   <a href=\'index.html\' >");
document.writeln("                       <h1>{{sitename}}</h1>");
document.writeln("                      </a>");
document.writeln("                </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                <div class=\'nav navbar-nav navbar-right col-2\'>你好!{{user.username}}</div>");
document.writeln("               ");
document.writeln("");
document.writeln("                <div class=\'nav navbar-nav navbar-right col-1\'>");
document.writeln("                    <button class=\'btn btn-light\' @click=\'gotoClientPage()\'>");
document.writeln("                        <a >");
document.writeln("                            个人中心");
document.writeln("                            </span>");
document.writeln("                        </a>");
document.writeln("                    </button>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <div class=\'nav navbar-nav navbar-right cart col-2\'>");
document.writeln("                    <button class=\'btn btn-light\' @click=\'checkOut\'>");
document.writeln("                       <a >");
document.writeln("                                <span class=\'glyphicon glyphicon-shopping-cart \'>");
document.writeln("                                    <span class=\'badge badge-primary badge-pill\'>{{count_Num+countNum}}</span> CheckedOut");
document.writeln("                                   ");
document.writeln("                                </span>");
document.writeln("                            </span>");
document.writeln("                        </a>");
document.writeln("                    </button>");
document.writeln("                </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                <div class=\'nav navbar-nav navbar-right col-1\'>");
document.writeln("                    <button class=\'btn btn-light\' @click=\'logout()\'> ");
document.writeln("                        <a >");
document.writeln("                            退出登录");
document.writeln("                            </span>");
document.writeln("                        </a>");
document.writeln("                    </button>");
document.writeln("");
document.writeln("                </div>");
document.writeln("");
document.writeln("");
document.writeln("            </div>");
document.writeln("");
document.writeln("        </header>");
document.writeln("");
document.writeln("    </div>");